name: fp1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  flutter_widget_from_html: ^0.16.0
  sqflite: ^2.3.0
  path: ^1.8.3
  logger: ^1.1.0 
  shared_preferences: ^2.2.2
  mobile_scanner: ^6.0.7
  image_picker: ^1.0.0
  permission_handler: ^10.2.0 
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  flutter_colorpicker: ^1.0.3
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  supabase_flutter: ^2.8.0
  mailer: ^6.2.0
  pin_code_fields: ^8.0.0
  fl_chart: ^0.70.0
  pdf: ^3.11.1
  printing: ^5.13.1
  screenshot: ^2.1.0
  barcode_widget: ^2.0.3



  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/triste.png


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icone.png"
